### ISSUE TITLE
Missing title from generated HTML

### ISSUE THREAD

**Issue by julianpistorius** [cyverse/atmosphere-guides#13]
Problem: The generated HTML does not contain a title

**Comment by calvinmclean** [comment]
This can be fixed if we add `-f markdown_mmd` (input format MultiMarkdown) to the make script and add `title: WOW TITLE` to the top of `md` files. I don't think changing the input format to MMD would break anything else, so I think this is a good option.

Source: https://stackoverflow.com/a/28350322
