### ISSUE TITLE
Unintended indentation in code blocks

### ISSUE THREAD

**Issue by Tharon-C** [cyverse/atmosphere-guides#29]
In code blocks there is a lot of indentation after the first line that makes it hard to read.
This because the html is formated with indentation normally this does not affect the output text in the browser. However the `<pre>` used around the code block does. The solution is most likely to not indent the html using a ugly output flag. I haven't looked into that yet though.

<img width="1332" alt="screen shot 2017-09-14 at 12 27 34 pm" src="https://user-images.githubusercontent.com/7366338/30451318-20af4a98-9948-11e7-99d7-d10202dcb220.png">

**Comment by c-mart** [comment]
Thank you for fixing @calvinmclean :bowing_man: . This has bugged me for years!
